
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'server-monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:9000']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']


